/**
 * Custom Next.js Image Loader for Cloudflare R2
 *
 * This loader serves pre-optimized WebP images from R2 storage,
 * eliminating the need for Vercel's image optimization.
 *
 * Images are pre-optimized at 3 sizes: 640px, 1024px, 1920px
 * The loader selects the smallest size that satisfies the requested width.
 */

import type { ImageLoaderProps } from 'next/image';

// Import manifest at build time (generated by optimize-and-upload.mjs)
import imageManifest from './image-manifest.json';

// Available pre-optimized widths (must match CONFIG.sizes in optimize-and-upload.mjs)
const AVAILABLE_WIDTHS = [640, 1024, 1920] as const;

// Type for manifest entries
interface ManifestEntry {
  variants: Record<number, string>;
  originalSize: number;
  hash: string;
}

type ImageManifest = Record<string, ManifestEntry>;

const manifest = imageManifest as ImageManifest;

// Largest available width for fallback
const LARGEST_WIDTH = 1920;

/**
 * Select the best width variant for the requested size
 * Returns the smallest available width that is >= requested width
 */
function selectWidth(requestedWidth: number): number {
  for (const width of AVAILABLE_WIDTHS) {
    if (width >= requestedWidth) {
      return width;
    }
  }
  // If requested width is larger than all available, return largest
  return LARGEST_WIDTH;
}

/**
 * Check if a path is an external URL
 */
function isExternalUrl(src: string): boolean {
  return src.startsWith('http://') || src.startsWith('https://');
}

/**
 * Check if path is a local image that should use the loader
 */
function isLocalImage(src: string): boolean {
  return src.startsWith('/images/') && !src.includes('/placeholders/');
}

/**
 * Custom loader for Next.js Image component
 *
 * For images in the manifest: returns R2 URL for appropriate size variant
 * For placeholders/external: returns original URL
 */
export default function cloudflareR2Loader({
  src,
  width,
}: ImageLoaderProps): string {
  // External URLs pass through unchanged
  if (isExternalUrl(src)) {
    return src;
  }

  // Placeholders and other local assets pass through
  if (!isLocalImage(src)) {
    return src;
  }

  // Look up in manifest
  const entry = manifest[src];

  if (!entry) {
    // Not in manifest - return original path
    // This allows graceful fallback for images not yet migrated
    console.warn(`[cloudflare-loader] Image not in manifest: ${src}`);
    return src;
  }

  // Select appropriate width variant
  const selectedWidth = selectWidth(width);
  const variantUrl = entry.variants[selectedWidth];

  if (!variantUrl) {
    // Fallback to largest available
    const largestWidth = Math.max(...Object.keys(entry.variants).map(Number));
    return entry.variants[largestWidth] || src;
  }

  return variantUrl;
}

/**
 * Get all available variants for an image
 * Useful for generating srcset manually
 */
export function getImageVariants(src: string): Record<number, string> | null {
  if (!isLocalImage(src)) {
    return null;
  }

  const entry = manifest[src];
  return entry?.variants || null;
}

/**
 * Check if an image has been migrated to R2
 */
export function isImageMigrated(src: string): boolean {
  return src in manifest;
}

/**
 * Get the R2 URL for an image at a specific width
 * Returns null if not in manifest
 */
export function getR2Url(src: string, width: number = 1024): string | null {
  const entry = manifest[src];
  if (!entry) return null;

  const selectedWidth = selectWidth(width);
  return entry.variants[selectedWidth] || null;
}
