import fs from 'node:fs';
import path from 'node:path';
import type { z } from 'zod';
import type { ContentItem } from './content-core';
import { defineContentLoader } from './content-loader';
import { tapestrySchema } from './content-schemas';
import imageManifest from './image-manifest.json';

// Define the possible status values as an enum
export type TapestryStatus =
  | 'Not Started'
  | 'Designed'
  | 'In Production'
  | 'Finished';

// Define the structure for timeline events
export interface TimelineEvent {
  date: string;
  title: string;
  description: string;
}

// Define the structure for resources
export interface TapestryResource {
  title: string;
  description: string;
  kind: string;
  url: string;
}

// Validate that a status is one of the allowed values
export function isValidStatus(status: string): status is TapestryStatus {
  return ['Not Started', 'Designed', 'In Production', 'Finished'].includes(
    status,
  );
}

export interface TapestryEntry {
  slug: string;
  title: string;
  summary: string;
  thumbnail: string;
  background_color: string;
  content: string;
  imagePath?: string;
  artworkPath?: string;
  audioPath?: string;
  audioDescription?: string;
  colony?: string | null;
  status: TapestryStatus;
  timelineEvents?: TimelineEvent[];
  resources?: TapestryResource[];
}

// Keep this for backward compatibility with image/audio finding functions (used in helper functions)
// const tapestryDirectory = path.join(process.cwd(), 'content/tapestries');

// Format preference: webp/jpg/png route through the R2 manifest; avif is a
// last-resort fallback (served by Vercel) so a missing webp/jpg variant
// doesn't silently fall back to the placeholder SVG.
const IMAGE_FORMAT_PRIORITY = ['.webp', '.jpg', '.jpeg', '.png', '.avif'];

// Responsive variants carry a -<width>w suffix before the extension
// (e.g. colony-main-1024w.webp), generated by scripts/optimize-and-upload.mjs.
const RESPONSIVE_VARIANT_RE = /-\d+w\.[a-z0-9]+$/i;

function isResponsiveVariant(file: string): boolean {
  return RESPONSIVE_VARIANT_RE.test(file);
}

/**
 * List the image filenames available for a tapestry.
 *
 * Two sources, unioned. The filesystem is authoritative for anything not yet
 * migrated to R2, but files ARE removed from public/ once they are on the CDN
 * (see VERCEL_USAGE_INVESTIGATION.md) — so a filesystem-only read makes a
 * migrated image invisible to every resolver below.
 *
 * That is not hypothetical: the thirteen mounted-tapestry photographs were
 * uploaded to R2 and then deleted from public/ in commit 235abb8, after which
 * findPhotoInDirectory silently found nothing and every tapestry page fell
 * through to the original artwork. The photographs were live on the CDN the
 * whole time. Caught 2026-09-01.
 *
 * The manifest is keyed by the ORIGINAL path (e.g. /images/tapestries/
 * delaware/delaware-photo.jpg); the loader maps that to the R2 variant at
 * render time, so returning the original filename here is correct.
 */
function listTapestryImageFiles(tapestrySlug: string): string[] {
  const names = new Set<string>();

  const dir = path.join(
    process.cwd(),
    'public/images/tapestries',
    tapestrySlug,
  );
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) names.add(f);
  }

  const prefix = `/images/tapestries/${tapestrySlug}/`;
  for (const key of Object.keys(imageManifest)) {
    if (key.startsWith(prefix)) {
      const rest = key.slice(prefix.length);
      if (!rest.includes('/')) names.add(rest);
    }
  }

  return [...names];
}

/**
 * Find one image file by format priority. Per format: prefer the
 * `preferWidth` responsive variant when given, then fall back to either a
 * non-variant original (`fallback: 'original'`) or any matching file
 * (`fallback: 'any'`).
 */
function findTapestryFile(
  files: string[],
  opts: {
    match: (lowerFile: string) => boolean;
    preferWidth?: string;
    fallback: 'original' | 'any';
  },
): string | undefined {
  for (const format of IMAGE_FORMAT_PRIORITY) {
    if (opts.preferWidth) {
      const variant = files.find(
        (file) =>
          path.extname(file).toLowerCase() === format &&
          opts.match(file.toLowerCase()) &&
          file.includes(opts.preferWidth as string),
      );
      if (variant) return variant;
    }
    const fallbackHit = files.find(
      (file) =>
        path.extname(file).toLowerCase() === format &&
        opts.match(file.toLowerCase()) &&
        (opts.fallback === 'any' || !isResponsiveVariant(file)),
    );
    if (fallbackHit) return fallbackHit;
  }
  return undefined;
}

// Main display image: prefer a file named *main* (1024w variant, then
// original), else any non-thumbnail image.
function findImageInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  if (files.length === 0) return null;

  const file =
    findTapestryFile(files, {
      match: (lower) => lower.includes('main'),
      preferWidth: '-1024w',
      fallback: 'original',
    }) ??
    findTapestryFile(files, {
      match: (lower) => !lower.includes('thumbnail'),
      preferWidth: '-1024w',
      fallback: 'original',
    });

  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

// PHOTOGRAPH of the finished, mounted tapestry: {slug}-photo.*. Preferred
// over the resolver for main image and thumbnail.
export function findPhotoInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const file = findTapestryFile(files, {
    match: (lower) => lower.includes('-photo'),
    fallback: 'any',
  });
  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

// ORIGINAL ARTWORK (the design illustration the stitchers worked from):
// {slug}-tapestry-* files excluding thumbnails. Artwork naming is
// inconsistent across states, so match on "-tapestry-" and exclude
// "thumbnail".
export function findArtworkInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const file = findTapestryFile(files, {
    match: (lower) =>
      lower.includes('-tapestry-') && !lower.includes('thumbnail'),
    preferWidth: '-1024w',
    fallback: 'any',
  });
  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

/**
 * Gallery texture image: prefer the `-fineart-gallery-` variants (real
 * stitched-textile photographs, generated by
 * scripts/generate-gallery-textures.mjs), then the non-thumbnail
 * `-tapestry-` variant at the preferred width (webp preferred over jpg),
 * falling back to 1024w, then to any non-thumbnail tapestry image. Used by
 * the 3D gallery, which wants an exact responsive variant rather than the
 * main-display resolver's pick.
 */
export function findGalleryImage(
  tapestrySlug: string,
  prefer: '1920w' | '1024w',
): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const isTapestryImage = (lower: string): boolean =>
    lower.includes('-tapestry-') && !lower.includes('thumbnail');

  const file =
    findTapestryFile(files, {
      match: (lower) =>
        lower.includes('-fineart-gallery-') && lower.includes(`-${prefer}`),
      fallback: 'any',
    }) ??
    findTapestryFile(files, {
      match: (lower) => isTapestryImage(lower) && lower.includes(`-${prefer}`),
      fallback: 'any',
    }) ??
    findTapestryFile(files, {
      match: (lower) => isTapestryImage(lower) && lower.includes('-1024w'),
      fallback: 'any',
    }) ??
    findTapestryFile(files, {
      match: isTapestryImage,
      preferWidth: '-1024w',
      fallback: 'any',
    });

  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

/**
 * Gallery tour-sheet thumbnail: a `*thumbnail*` variant (640w preferred),
 * falling back to a 640w tapestry variant for slugs without thumbnails
 * (e.g. connecticut, delaware, maryland).
 */
export function findGalleryThumb(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const file =
    findTapestryFile(files, {
      match: (lower) => lower.includes('thumbnail'),
      preferWidth: '-640w',
      fallback: 'any',
    }) ??
    findTapestryFile(files, {
      match: (lower) => lower.includes('-tapestry') && lower.includes('-640w'),
      fallback: 'any',
    });

  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

function findAudioInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const audioFile = files.find((file) => {
    const ext = path.extname(file).toLowerCase();
    return (
      ['.mp3', '.wav', '.ogg', '.m4a'].includes(ext) &&
      (file.toLowerCase().includes('audio') ||
        file.toLowerCase().includes('description'))
    );
  });
  return audioFile ? `/images/tapestries/${tapestrySlug}/${audioFile}` : null;
}

// Thumbnail: frontmatter override, then finished-photo, then a *thumbnail*
// file (640w variant preferred), then the main image, then the placeholder.
function resolveThumbnail(
  slug: string,
  files: string[],
  frontmatterThumbnail: string | undefined,
  photoPath: string | null,
  imagePath: string | null,
): string {
  if (frontmatterThumbnail) return frontmatterThumbnail;
  if (photoPath) return photoPath;

  const thumbnailFile = findTapestryFile(files, {
    match: (lower) => lower.includes('thumbnail'),
    preferWidth: '-640w',
    fallback: 'original',
  });
  if (thumbnailFile) return `/images/tapestries/${slug}/${thumbnailFile}`;
  if (imagePath) return imagePath;
  return '/images/placeholders/tapestry-placeholder.svg?height=600&width=800';
}

/**
 * Map validated tapestry frontmatter + raw item to a TapestryEntry. Shared by
 * getAllTapestries and getTapestryBySlug so image/status/thumbnail rules live
 * in exactly one place.
 */
function mapTapestry(
  data: z.infer<typeof tapestrySchema>,
  item: ContentItem,
): TapestryEntry {
  const slug = item.slug;
  const files = listTapestryImageFiles(slug);

  const status =
    data.status && isValidStatus(data.status) ? data.status : 'Not Started';

  const photoPath = findPhotoInDirectory(slug);
  const imagePath = photoPath || findImageInDirectory(slug);
  const artworkPath = findArtworkInDirectory(slug);
  const audioPath = findAudioInDirectory(slug);
  const thumbnail = resolveThumbnail(
    slug,
    files,
    data.thumbnail,
    photoPath,
    imagePath,
  );

  return {
    slug,
    title: data.title,
    summary: data.summary,
    thumbnail,
    background_color: data.background_color,
    content: item.content,
    // exactOptionalPropertyTypes: only set these keys when a path was found,
    // rather than assigning an explicit `undefined` value.
    ...(imagePath ? { imagePath } : {}),
    ...(artworkPath ? { artworkPath } : {}),
    ...(audioPath ? { audioPath } : {}),
    audioDescription:
      data.audioDescription ||
      `Audio description of the ${data.title} tapestry`,
    colony: data.colony || null,
    status,
    timelineEvents: data.timelineEvents || [],
    resources: data.resources || [],
  };
}

const tapestriesLoader = defineContentLoader<
  TapestryEntry,
  typeof tapestrySchema
>({
  contentType: 'tapestries',
  label: 'tapestry',
  schema: tapestrySchema,
  map: mapTapestry,
  sort: (a, b) => a.title.localeCompare(b.title),
});

/** Get all tapestries, sorted by title. */
export const getAllTapestries = tapestriesLoader.getAll;

/** Get a single tapestry by slug, or null if not found. */
export const getTapestryBySlug = tapestriesLoader.getBySlug;
