import { getAllContent, getContentBySlug } from './content-core';
import {
  tapestrySchema,
  validateFrontmatter,
  FrontmatterValidationError,
} from './content-schemas';
import fs from 'fs';
import path from 'path';

// Define the possible status values as an enum
export type TapestryStatus =
  | 'Not Started'
  | 'Designed'
  | 'In Production'
  | 'Finished';

// Define the structure for timeline events
export interface TimelineEvent {
  date: string;
  title: string;
  description: string;
}

// Define the structure for resources
export interface TapestryResource {
  title: string;
  description: string;
  kind: string;
  url: string;
}

// Validate that a status is one of the allowed values
export function isValidStatus(status: string): status is TapestryStatus {
  return ['Not Started', 'Designed', 'In Production', 'Finished'].includes(
    status,
  );
}

export interface TapestryEntry {
  slug: string;
  title: string;
  summary: string;
  thumbnail: string;
  background_color: string;
  content: string;
  imagePath?: string;
  artworkPath?: string;
  audioPath?: string;
  audioDescription?: string;
  colony?: string | null;
  status: TapestryStatus;
  timelineEvents?: TimelineEvent[];
  resources?: TapestryResource[];
}

// Keep this for backward compatibility with image/audio finding functions (used in helper functions)
// const tapestryDirectory = path.join(process.cwd(), 'content/tapestries');

// Format preference: webp/jpg/png route through the R2 manifest; avif is a
// last-resort fallback (served by Vercel) so a missing webp/jpg variant
// doesn't silently fall back to the placeholder SVG.
const IMAGE_FORMAT_PRIORITY = ['.webp', '.jpg', '.jpeg', '.png', '.avif'];

// Responsive variants carry a -<width>w suffix before the extension
// (e.g. colony-main-1024w.webp), generated by scripts/optimize-and-upload.mjs.
const RESPONSIVE_VARIANT_RE = /-\d+w\.[a-z0-9]+$/i;

function isResponsiveVariant(file: string): boolean {
  return RESPONSIVE_VARIANT_RE.test(file);
}

/** List files in public/images/tapestries/{slug}, or [] if the dir is absent. */
function listTapestryImageFiles(tapestrySlug: string): string[] {
  const dir = path.join(
    process.cwd(),
    'public/images/tapestries',
    tapestrySlug,
  );
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir);
}

/**
 * Find one image file by format priority. Per format: prefer the
 * `preferWidth` responsive variant when given, then fall back to either a
 * non-variant original (`fallback: 'original'`) or any matching file
 * (`fallback: 'any'`).
 */
function findTapestryFile(
  files: string[],
  opts: {
    match: (lowerFile: string) => boolean;
    preferWidth?: string;
    fallback: 'original' | 'any';
  },
): string | undefined {
  for (const format of IMAGE_FORMAT_PRIORITY) {
    if (opts.preferWidth) {
      const variant = files.find(
        (file) =>
          path.extname(file).toLowerCase() === format &&
          opts.match(file.toLowerCase()) &&
          file.includes(opts.preferWidth as string),
      );
      if (variant) return variant;
    }
    const fallbackHit = files.find(
      (file) =>
        path.extname(file).toLowerCase() === format &&
        opts.match(file.toLowerCase()) &&
        (opts.fallback === 'any' || !isResponsiveVariant(file)),
    );
    if (fallbackHit) return fallbackHit;
  }
  return undefined;
}

// Main display image: prefer a file named *main* (1024w variant, then
// original), else any non-thumbnail image.
function findImageInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  if (files.length === 0) return null;

  const file =
    findTapestryFile(files, {
      match: (lower) => lower.includes('main'),
      preferWidth: '-1024w',
      fallback: 'original',
    }) ??
    findTapestryFile(files, {
      match: (lower) => !lower.includes('thumbnail'),
      preferWidth: '-1024w',
      fallback: 'original',
    });

  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

// PHOTOGRAPH of the finished, mounted tapestry: {slug}-photo.*. Preferred
// over the resolver for main image and thumbnail.
export function findPhotoInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const file = findTapestryFile(files, {
    match: (lower) => lower.includes('-photo'),
    fallback: 'any',
  });
  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

// ORIGINAL ARTWORK (the design illustration the stitchers worked from):
// {slug}-tapestry-* files excluding thumbnails. Artwork naming is
// inconsistent across states, so match on "-tapestry-" and exclude
// "thumbnail".
export function findArtworkInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const file = findTapestryFile(files, {
    match: (lower) =>
      lower.includes('-tapestry-') && !lower.includes('thumbnail'),
    preferWidth: '-1024w',
    fallback: 'any',
  });
  return file ? `/images/tapestries/${tapestrySlug}/${file}` : null;
}

function findAudioInDirectory(tapestrySlug: string): string | null {
  const files = listTapestryImageFiles(tapestrySlug);
  const audioFile = files.find((file) => {
    const ext = path.extname(file).toLowerCase();
    return (
      ['.mp3', '.wav', '.ogg', '.m4a'].includes(ext) &&
      (file.toLowerCase().includes('audio') ||
        file.toLowerCase().includes('description'))
    );
  });
  return audioFile ? `/images/tapestries/${tapestrySlug}/${audioFile}` : null;
}

// Function to get carousel images as TapestryEntry-like objects
export function getCarouselImages(): TapestryEntry[] {
  try {
    const carouselPath = path.join(process.cwd(), 'public/images/carousel');

    if (!fs.existsSync(carouselPath)) {
      console.warn('Carousel directory not found');
      return [];
    }

    const files = fs.readdirSync(carouselPath);
    const imageFiles = files.filter((file) => {
      const ext = path.extname(file).toLowerCase();
      return ['.jpg', '.jpeg', '.png', '.webp', '.avif'].includes(ext);
    });

    // Sort files by name to ensure consistent ordering
    imageFiles.sort();

    return imageFiles.map((file, index) => ({
      slug: `carousel-${index + 1}`,
      title: `Carousel Image ${index + 1}`,
      summary: '',
      thumbnail: `/images/carousel/${file}`,
      background_color: 'bg-colonial-navy',
      content: '',
      imagePath: `/images/carousel/${file}`,
      colony: null,
      status: 'In Progress' as TapestryStatus,
      timelineEvents: [],
    }));
  } catch (error) {
    console.error('Error loading carousel images:', error);
    return [];
  }
}

export async function getAllTapestries(): Promise<TapestryEntry[]> {
  try {
    // Use content-core to get all tapestry content
    const tapestryContent = await getAllContent('tapestries');

    const tapestries: TapestryEntry[] = [];

    for (const item of tapestryContent) {
      const data = validateFrontmatter(tapestrySchema, item.frontmatter, {
        contentType: 'tapestry',
        slug: item.slug,
      });
      const content = item.content;
      const slug = item.slug;

      // Validate status or set default
      const status =
        data['status'] && isValidStatus(data['status'])
          ? data['status']
          : 'Not Started';

      // Find the main image in the directory
      const photoPath = findPhotoInDirectory(slug);
      const imagePath = photoPath || findImageInDirectory(slug);

      // Find audio description file
      const audioPath = findAudioInDirectory(slug);

      // Construct the thumbnail path - either from frontmatter or by convention
      // Updated to prefer optimized responsive variants over original files
      let thumbnail = data['thumbnail'] || photoPath;
      if (!thumbnail) {
        // Look for thumbnail in the public images directory
        const publicImagePath = path.join(
          process.cwd(),
          'public/images/tapestries',
          slug,
        );

        if (fs.existsSync(publicImagePath)) {
          const files = fs.readdirSync(publicImagePath);
          const formatPriority = ['.webp', '.jpg', '.jpeg', '.png', '.avif'];

          // Find optimized thumbnail variants first
          for (const format of formatPriority) {
            // Try responsive thumbnail variants (640w is good for thumbnails)
            const responsiveThumbnail = files.find((file) => {
              const ext = path.extname(file).toLowerCase();
              return (
                ext === format &&
                file.toLowerCase().includes('thumbnail') &&
                file.includes('-640w')
              );
            });

            if (responsiveThumbnail) {
              thumbnail = `/images/tapestries/${slug}/${responsiveThumbnail}`;
              break;
            }

            // Fall back to original thumbnail
            const originalThumbnail = files.find((file) => {
              const ext = path.extname(file).toLowerCase();
              return (
                ext === format &&
                file.toLowerCase().includes('thumbnail') &&
                !file.includes('-640w') &&
                !file.includes('-1024w') &&
                !file.includes('-1920w') &&
                !file.includes('-2560w') &&
                !file.includes('-400w') &&
                !file.includes('-1280w') &&
                !file.includes('-200w') &&
                !file.includes('-600w') &&
                !file.includes('-300w') &&
                !file.includes('-900w')
              );
            });

            if (originalThumbnail) {
              thumbnail = `/images/tapestries/${slug}/${originalThumbnail}`;
              break;
            }
          }

          // If no thumbnail found, use main image as fallback
          if (!thumbnail && imagePath) {
            thumbnail = imagePath;
          } else if (!thumbnail) {
            // Use placeholder as last resort
            thumbnail =
              '/images/placeholders/tapestry-placeholder.svg?height=600&width=800';
          }
        } else {
          // Use placeholder as last resort
          thumbnail =
            '/images/placeholders/tapestry-placeholder.svg?height=600&width=800';
        }
      }

      // Return the tapestry entry
      tapestries.push({
        slug,
        title: data['title'],
        summary: data['summary'],
        thumbnail: thumbnail || imagePath, // Use main image as fallback if no thumbnail
        background_color: data['background_color'],
        content,
        imagePath,
        artworkPath: findArtworkInDirectory(slug) || undefined,
        audioPath,
        audioDescription:
          data['audioDescription'] ||
          `Audio description of the ${data['title']} tapestry`,
        colony: data['colony'] || null,
        status,
        timelineEvents: data['timelineEvents'] || [],
        resources: data['resources'] || [],
      } as TapestryEntry);
    }

    // Sort tapestries by title
    return tapestries.sort((a, b) => a.title.localeCompare(b.title));
  } catch (error) {
    if (error instanceof FrontmatterValidationError) throw error;
    console.error('Error getting all tapestries:', error);
    return [];
  }
}

export async function getTapestryBySlug(
  slug: string,
): Promise<TapestryEntry | null> {
  try {
    // Use content-core to get the specific tapestry content
    const tapestryItem = await getContentBySlug('tapestries', slug);

    if (!tapestryItem) {
      return null;
    }

    const data = validateFrontmatter(tapestrySchema, tapestryItem.frontmatter, {
      contentType: 'tapestry',
      slug,
    });
    const content = tapestryItem.content;

    // Validate status or set default
    const status =
      data['status'] && isValidStatus(data['status'])
        ? data['status']
        : 'Not Started';

    // Find the main image in the directory
    const photoPath = findPhotoInDirectory(slug);
    const imagePath = photoPath || findImageInDirectory(slug);

    // Find audio description file
    const audioPath = findAudioInDirectory(slug);

    // Construct the thumbnail path - either from frontmatter or by convention
    let thumbnail = data['thumbnail'] || photoPath;
    if (!thumbnail) {
      // Look for thumbnail in the public images directory
      const publicImagePath = path.join(
        process.cwd(),
        'public/images/tapestries',
        slug,
      );

      if (fs.existsSync(publicImagePath)) {
        const thumbnailFile = fs
          .readdirSync(publicImagePath)
          .find((file) => file.toLowerCase().includes('thumbnail'));

        if (thumbnailFile) {
          thumbnail = `/images/tapestries/${slug}/${thumbnailFile}`;
        } else if (imagePath) {
          // Use main image as fallback if available
          thumbnail = imagePath;
        } else {
          // Use placeholder as last resort
          thumbnail = '/images/placeholders/placeholder.svg';
        }
      } else {
        // Use placeholder as last resort
        thumbnail = '/images/placeholders/placeholder.svg';
      }
    }

    return {
      slug,
      title: data['title'],
      summary: data['summary'],
      thumbnail: thumbnail || imagePath, // Use main image as fallback if no thumbnail
      background_color: data['background_color'],
      content,
      imagePath,
      artworkPath: findArtworkInDirectory(slug) || undefined,
      audioPath,
      audioDescription:
        data['audioDescription'] ||
        `Audio description of the ${data['title']} tapestry`,
      colony: data['colony'] || null,
      status,
      timelineEvents: data['timelineEvents'] || [],
      resources: data['resources'] || [],
    } as TapestryEntry;
  } catch (error) {
    if (error instanceof FrontmatterValidationError) throw error;
    console.error(`Error getting tapestry ${slug}:`, error);
    return null;
  }
}
